---
# tasks file for base-config
- name: Congigure instance to use the organization's local yum repository
  get_url:
    url: "{{ instance_repo_url }}"
    dest: "{{ instance_repo_dir }}/internal.repo"
    force: yes
    owner: root
    group: root
    mode: "0644"
