---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: ospcloud
    region_name: RegionOne
  register: result
  tags:
    - instance-info
    - instance-stop

- name: Delete instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
    wait: yes
  loop: "{{ result.ansible_facts.openstack_servers }}"
  tags: instance-stop
