- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Curl website
    uri:
      url: "http://{{ item.interface_ip }}"
      return_content: yes
    register: webpage
    loop: "{{ openstack_info.openstack_servers }}"
    tags:
      - osp.smoke
#- debug: var=webpage.results

  - name: Fail if 'Ansible has done its job' is not in the page content
    debug: msg="'Ansible has done its job' loaded up in page content successfully"
    failed_when: "item.status != 200 or 'Ansible has done its job' not in item.content"
    with_items: "{{ webpage.results }}"
    tags:
      - osp.smoke
