- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "webpage.status != 200 or 'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
