- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: testing connectivity to frontends:
  ping:
    data: "ssh connectivity OK"
  retries: 3

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: testing connectivity to apps:
  ping:
    data: "ssh connectivity OK"
  retries: 3

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: testing connectivity to appdbs:
  ping:
    data: "ssh connectivity OK"
  retries: 3

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
